# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.h2.console.enabled=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# # Swagger Configuration
# springdoc.api-docs.path=/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html


# spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_db
# spring.datasource.username=postgres
# spring.datasource.password=1234
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update


# # Enable SQL logging (optional, for debugging purposes)
# spring.jpa.show-sql=true

# ===============================
# Database Configuration - PostgreSQL
# ===============================
spring.datasource.url= jdbc:postgresql://localhost:5432/springboot_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Hibernate & JPA Configuration
# ===============================
# Show SQL queries in the console (for debugging)
spring.jpa.show-sql=true

# Format SQL output (for better readability)
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Swagger Configuration (Optional)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
